"""
Explainable AI and Consistency Analysis Module (RQ3)
------------------------------------------------------
Author: Senior Data Analytics Engineer / Team Members
Methodology: CRISP-DM
Dataset: CDC Diabetes Health Indicators (Cleaned)

This script performs the XAI and consistency analysis phase (Phase 5) to answer RQ3:
"Are the explanations generated by the best-performing machine learning model
statistically consistent with evidence obtained from traditional hypothesis testing?"

It applies:
- SHAP (SHapley Additive exPlanations) for global & local interpretation.
- Statistical Consistency Analysis comparing SHAP ranks with hypothesis testing effect sizes.

All outputs are saved in results/xai/.
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier
import shap

# Monkey patch matplotlib.pyplot.arrow to fix a bug in the shap library's waterfall plot
# where the shaft of arrows with small SHAP values can point in the wrong direction (due to missing safety checks).
original_arrow = plt.arrow

def patched_arrow(x, y, dx, dy, **kwargs):
    color = kwargs.get("color", "")
    
    # Identify positive vs negative arrow based on RGB values or string hex codes
    is_positive = False
    is_negative = False
    
    if isinstance(color, (tuple, list, np.ndarray)) and len(color) >= 3:
        # RGB / RGBA: Red component dominates for positive, Blue dominates for negative
        r, g, b = color[0], color[1], color[2]
        if r > b:
            is_positive = True
        else:
            is_negative = True
    else:
        color_str = str(color).lower()
        if "#ff" in color_str or "red" in color_str or "pink" in color_str:
            is_positive = True
        elif "#00" in color_str or "blue" in color_str:
            is_negative = True

    if is_positive:
        if dx < 0:
            dx = 1e-6
    elif is_negative:
        if dx > 0:
            dx = -1e-6
            
    return original_arrow(x, y, dx, dy, **kwargs)

plt.arrow = patched_arrow

# Define directory paths
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_PATH = BASE_DIR / "data" / "processed" / "diabetes_cleaned.csv"
XAI_DIR = BASE_DIR / "results" / "xai"
XAI_DIR.mkdir(parents=True, exist_ok=True)

def load_data(file_path: Path) -> pd.DataFrame:
    """Loads the cleaned dataset."""
    print(f"Loading cleaned dataset from: {file_path}")
    if not file_path.exists():
        raise FileNotFoundError(f"Cleaned dataset not found at {file_path}. Run preprocessing first.")
    df = pd.read_csv(file_path)
    return df

def train_best_model(X_train, y_train):
    """Trains the best-performing model (XGBoost) identified in RQ2."""
    print("\nTraining XGBoost model...")
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    
    # Train on DataFrame to keep feature names
    X_train_scaled_df = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
    
    model = XGBClassifier(
        n_estimators=100,
        max_depth=6,
        learning_rate=0.1,
        random_state=42,
        eval_metric="logloss",
        n_jobs=-1
    )
    model.fit(X_train_scaled_df, y_train)
    return model, scaler

def run_shap_analysis(model, X_test, scaler, y_test):
    """Computes SHAP values and saves global and local plots."""
    print("\nComputing SHAP values...")
    X_test_scaled = scaler.transform(X_test)
    X_test_scaled_df = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
    
    # Stratified sample 10,000 cases to speed up SHAP explainer
    X_test_sample = X_test_scaled_df.sample(n=10000, random_state=42)
    y_test_sample = y_test.loc[X_test_sample.index]
    
    # Initialize Tree Explainer
    explainer = shap.TreeExplainer(model)
    shap_values = explainer(X_test_sample)
    
    # Determine dimensionality of SHAP values
    if len(shap_values.values.shape) == 3:  # Binary sometimes returns (N, M, 2)
        # Take class 1 (diabetic)
        shap_imp = np.abs(shap_values.values[:, :, 1]).mean(axis=0)
        shap_values_to_plot = shap_values[:, :, 1]
    else:
        shap_imp = np.abs(shap_values.values).mean(axis=0)
        shap_values_to_plot = shap_values
        
    # Save SHAP feature importance data
    shap_imp_df = pd.DataFrame({
        "Variable": X_test.columns,
        "SHAP_Importance": shap_imp
    }).sort_values(by="SHAP_Importance", ascending=False)
    
    # 1. Global Summary Bar Plot
    plt.figure(figsize=(10, 6))
    shap.summary_plot(shap_values_to_plot, X_test_sample, plot_type="bar", show=False)
    plt.title("SHAP Global Feature Importance (Bar Plot)", fontsize=13, fontweight="bold", pad=20)
    plt.xlabel("Mean |SHAP Value| (Feature Importance)", fontsize=11, labelpad=10)
    plt.gcf().tight_layout()
    plt.savefig(XAI_DIR / "shap_summary_bar.png", dpi=300, bbox_inches="tight")
    plt.close()
    
    # 2. Global Beeswarm Summary Plot
    plt.figure(figsize=(10, 6))
    shap.summary_plot(shap_values_to_plot, X_test_sample, show=False)
    plt.title("SHAP Global Feature Impact (Beeswarm Plot)", fontsize=13, fontweight="bold", pad=20)
    plt.xlabel("SHAP Value (Impact on Model Output)", fontsize=11, labelpad=10)
    plt.gcf().tight_layout()
    plt.savefig(XAI_DIR / "shap_summary_dot.png", dpi=300, bbox_inches="tight")
    plt.close()
    
    # 3. Local Explanations (diabetic and healthy samples)
    y_prob_sample = model.predict_proba(X_test_sample)[:, 1]
    y_test_sample_arr = y_test_sample.values
    
    # Find a diabetic patient with high predicted risk
    diabetic_indices = np.where((y_test_sample_arr == 1) & (y_prob_sample > 0.6))[0]
    if len(diabetic_indices) > 0:
        idx_diabetic = diabetic_indices[0]
        plt.figure(figsize=(10, 6))
        shap.plots.waterfall(shap_values_to_plot[idx_diabetic], max_display=8, show=False)
        plt.title(f"SHAP Local Explanation (Diabetic Patient, Risk={y_prob_sample[idx_diabetic]:.2%})", fontsize=12, fontweight="bold", pad=15)
        plt.savefig(XAI_DIR / "shap_local_diabetic.png", dpi=300, bbox_inches="tight")
        plt.close()
        print(f"Saved local diabetic patient explanation at index {idx_diabetic} (Risk = {y_prob_sample[idx_diabetic]:.2%})")
        
    # Find a healthy patient with low predicted risk
    healthy_indices = np.where((y_test_sample_arr == 0) & (y_prob_sample < 0.1))[0]
    if len(healthy_indices) > 0:
        idx_healthy = healthy_indices[0]
        plt.figure(figsize=(10, 6))
        shap.plots.waterfall(shap_values_to_plot[idx_healthy], max_display=8, show=False)
        plt.title(f"SHAP Local Explanation (Healthy Patient, Risk={y_prob_sample[idx_healthy]:.2%})", fontsize=12, fontweight="bold", pad=15)
        plt.savefig(XAI_DIR / "shap_local_healthy.png", dpi=300, bbox_inches="tight")
        plt.close()
        print(f"Saved local healthy patient explanation at index {idx_healthy} (Risk = {y_prob_sample[idx_healthy]:.2%})")
        
    print("Saved all SHAP plots successfully.")
    return shap_imp_df

def perform_consistency_analysis(shap_imp_df):
    """Compares SHAP importance ranking with statistical hypothesis testing effect sizes."""
    print("\nPerforming Explanation Consistency Analysis...")
    
    stat_dir = BASE_DIR / "results" / "statistical_analysis"
    chi_path = stat_dir / "chi_square_results.csv"
    num_path = stat_dir / "numerical_results.csv"
    
    if not (chi_path.exists() and num_path.exists()):
        raise FileNotFoundError("Statistical results from Phase 2 not found. Run statistical analysis first.")
        
    chi_df = pd.read_csv(chi_path)
    num_df = pd.read_csv(num_path)
    chi_df.columns = chi_df.columns.str.strip()
    num_df.columns = num_df.columns.str.strip()
    
    # Construct a unified statistical df
    stat_list = []
    for _, row in chi_df.iterrows():
        stat_list.append({
            "Variable": row["Variable"].strip(),
            "p-value": float(row["p-value"]),
            "Effect_Size": float(row["Cramér's V"]),
            "Effect_Size_Type": "Cramér's V",
            "Stat_Interpretation": row["Effect Size Interpretation"].strip()
        })
    for _, row in num_df.iterrows():
        stat_list.append({
            "Variable": row["Variable"].strip(),
            "p-value": float(row["MWU p-value"]),
            # Rank-Biserial is continuous effect size; take absolute value
            "Effect_Size": abs(float(row["Rank-Biserial Correlation"])),
            "Effect_Size_Type": "Abs Rank-Biserial",
            "Stat_Interpretation": "Medium" if row["Variable"].strip() == "BMI" else ("Small" if row["Variable"].strip() == "PhysHlth" else "Negligible")
        })
        
    stat_df = pd.DataFrame(stat_list)
    
    # Merge SHAP importance and Statistical parameters
    merged = pd.merge(shap_imp_df, stat_df, on="Variable")
    merged["SHAP_Rank"] = merged["SHAP_Importance"].rank(ascending=False).astype(int)
    merged["Stat_Rank"] = merged["Effect_Size"].rank(ascending=False).astype(int)
    merged = merged.sort_values(by="SHAP_Rank")
    
    # Categorize into 3 groups based on significance (p < 0.05) and SHAP rank
    # Note: all features in this massive dataset are p < 0.05, so we analyze SHAP Rank <= 10 (High Importance)
    groups = []
    for _, row in merged.iterrows():
        var = row["Variable"]
        p_val = row["p-value"]
        rank = row["SHAP_Rank"]
        
        if p_val < 0.05 and rank <= 10:
            grp = "Group 1: Strong Agreement (Significant & High SHAP)"
        elif p_val < 0.05 and rank > 10:
            grp = "Group 2: Under-represented (Significant & Low SHAP)"
        elif p_val >= 0.05 and rank <= 10:
            grp = "Group 3: Potential Interaction (Insignificant & High SHAP)"
        else:
            grp = "Group 4: Insignificant & Low SHAP"
            
        groups.append(grp)
        
    merged["Consistency_Group"] = groups
    
    # Save the consistency analysis csv
    merged.to_csv(XAI_DIR / "explanation_consistency.csv", index=False)
    print("Saved explanation_consistency.csv")
    
    # Print the grouped features
    print("\n--- Explanation Consistency Analysis Groups ---")
    g1 = merged[merged["Consistency_Group"].str.startswith("Group 1")]["Variable"].tolist()
    g2 = merged[merged["Consistency_Group"].str.startswith("Group 2")]["Variable"].tolist()
    g3 = merged[merged["Consistency_Group"].str.startswith("Group 3")]["Variable"].tolist()
    
    print(f"Group 1 (Strong Agreement - Top 10 SHAP & Stat Significant): {g1}")
    print(f"Group 2 (Under-represented in model - Low SHAP & Stat Significant): {g2}")
    print(f"Group 3 (Potential Interaction/Nonlinear - High SHAP & Stat Insignificant): {g3}")

def main():
    print("=== Phase 5: Explainable AI and Consistency Analysis ===")
    
    # 1. Load data
    try:
        df = load_data(DATA_PATH)
    except FileNotFoundError as e:
        print(e)
        return
        
    # Split features and target
    X = df.drop(columns=["Diabetes_binary"])
    y = df["Diabetes_binary"]
    
    # Stratified Train-Test Split (consistent with model_training.py)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=42
    )
    
    # 2. Train model
    model, scaler = train_best_model(X_train, y_train)
    
    # 3. Compute SHAP Values and Visualizations
    shap_imp_df = run_shap_analysis(model, X_test, scaler, y_test)
    
    # 4. Consistency Analysis
    perform_consistency_analysis(shap_imp_df)
    
    print("\n=== Explainable AI Module Completed Successfully ===")

if __name__ == "__main__":
    main()
