"""
Explainable AI and Statistical-SHAP Evidence Alignment Module (RQ3)
--------------------------------------------------------------------
Author: Senior Data Analytics Engineer / Team Members
Methodology: CRISP-DM
Dataset: CDC Diabetes Health Indicators (Cleaned)

This script performs the Explainable AI (XAI) and Evidence Alignment phase (Phase 5) to answer RQ3:
"Are the explanations generated by the best-performing machine learning model
statistically consistent with evidence obtained from traditional hypothesis testing?"

Rigorously adheres to:
1. Dynamically loads the selected model pipeline and metadata from Phase 4 (modeling phase).
2. Calculates post-hoc SHAP explanations on an independent sample of the Holdout Test Set.
3. Classifies features into four evidence alignment groups based on standardized Effect Size heuristics
   and SHAP importance ranks (without relying on sample-size inflated p-values or unsupported interaction claims).
4. Computes quantitative consensus metrics (Top-10 overlap, Jaccard similarity, Spearman rank correlation).

All outputs are saved in results/xai/ and docs/figures/.
"""

import json
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from scipy.stats import spearmanr
from sklearn.model_selection import train_test_split
import shap

# Monkey patch matplotlib.pyplot.arrow for safety in SHAP waterfall plots
original_arrow = plt.arrow

def patched_arrow(x, y, dx, dy, **kwargs):
    color = kwargs.get("color", "")
    is_positive = False
    is_negative = False
    
    if isinstance(color, (tuple, list, np.ndarray)) and len(color) >= 3:
        r, g, b = color[0], color[1], color[2]
        if r > b:
            is_positive = True
        else:
            is_negative = True
    else:
        color_str = str(color).lower()
        if "#ff" in color_str or "red" in color_str or "pink" in color_str:
            is_positive = True
        elif "#00" in color_str or "blue" in color_str:
            is_negative = True

    if is_positive and dx < 0:
        dx = 1e-6
    elif is_negative and dx > 0:
        dx = -1e-6
            
    return original_arrow(x, y, dx, dy, **kwargs)

plt.arrow = patched_arrow

# Define directory paths
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_PATH = BASE_DIR / "data" / "processed" / "diabetes_cleaned.csv"
RESULTS_MODELING_DIR = BASE_DIR / "results" / "modeling"
RESULTS_STAT_DIR = BASE_DIR / "results" / "statistical_analysis"
XAI_DIR = BASE_DIR / "results" / "xai"
DOCS_FIG_DIR = BASE_DIR / "docs" / "figures"

XAI_DIR.mkdir(parents=True, exist_ok=True)
DOCS_FIG_DIR.mkdir(parents=True, exist_ok=True)

LABEL_MAPPING = {
    "HighBP": "High Blood Pressure",
    "HighChol": "High Cholesterol",
    "CholCheck": "Cholesterol Check (5 Years)",
    "Smoker": "Tobacco Smoker Status",
    "Stroke": "Stroke History",
    "HeartDiseaseorAttack": "Heart Disease or Attack History",
    "PhysActivity": "Physical Activity Indicator",
    "Fruits": "Fruit Consumption Daily",
    "Veggies": "Vegetable Consumption Daily",
    "HvyAlcoholConsump": "Heavy Alcohol Consumption",
    "AnyHealthcare": "Healthcare Coverage Access",
    "NoDocbcCost": "Doctor Cost Barrier",
    "GenHlth": "Self-Rated General Health",
    "DiffWalk": "Difficulty Walking",
    "Sex": "Biological Sex",
    "Age": "Age Category (13 levels)",
    "Education": "Education Level",
    "Income": "Income Bracket",
    "BMI": "Body Mass Index",
    "MentHlth": "Mental Unhealthy Days",
    "PhysHlth": "Physical Unhealthy Days"
}

def load_data(file_path: Path) -> pd.DataFrame:
    """Loads the cleaned dataset."""
    print(f"Loading cleaned dataset from: {file_path}")
    if not file_path.exists():
        raise FileNotFoundError(f"Cleaned dataset not found at {file_path}. Run preprocessing first.")
    df = pd.read_csv(file_path)
    return df

def load_selected_model():
    """Loads selected model pipeline and selection metadata from Phase 4."""
    selection_file = RESULTS_MODELING_DIR / "model_selection.json"
    model_file = RESULTS_MODELING_DIR / "final_model.joblib"
    
    if not (selection_file.exists() and model_file.exists()):
        raise FileNotFoundError("Model selection artifacts not found. Run model_training.py first.")
        
    with open(selection_file, "r", encoding="utf-8") as f:
        metadata = json.load(f)
        
    final_pipeline = joblib.load(model_file)
    selected_model_name = metadata["selected_model"]
    selected_threshold = metadata["selected_threshold"]
    
    print(f"Loaded selected model: {selected_model_name}")
    print(f"Selected screening threshold: {selected_threshold:.2f}")
    return final_pipeline, selected_model_name, selected_threshold, metadata

def run_shap_analysis(pipeline, model_name, X_test, y_test):
    """Computes SHAP values on independent holdout test sample and generates summary & local plots."""
    print(f"\nComputing SHAP values for final fitted pipeline ({model_name})...")
    
    # Extract classifier step and preprocessor if present
    if hasattr(pipeline, "named_steps"):
        preprocessor = pipeline.named_steps.get("preprocessor", None)
        classifier = pipeline.named_steps["classifier"]
    else:
        preprocessor = None
        classifier = pipeline
        
    # Preprocess X_test if preprocessor exists
    if preprocessor is not None:
        X_test_trans = preprocessor.transform(X_test)
        if hasattr(preprocessor, "get_feature_names_out"):
            feature_names = preprocessor.get_feature_names_out()
        else:
            feature_names = [f"feat_{i}" for i in range(X_test_trans.shape[1])]
        X_test_df = pd.DataFrame(X_test_trans, columns=feature_names, index=X_test.index)
    else:
        X_test_df = X_test.copy()
        
    # Sample up to 10,000 cases from test set for post-hoc explanation
    n_sample = min(10000, len(X_test_df))
    X_test_sample = X_test_df.sample(n=n_sample, random_state=42)
    X_raw_sample = X_test.loc[X_test_sample.index]
    y_test_sample = y_test.loc[X_test_sample.index]
    
    # Initialize appropriate SHAP Explainer
    if "XGB" in model_name or "Random Forest" in model_name or "Decision Tree" in model_name:
        explainer = shap.TreeExplainer(classifier)
        shap_values = explainer(X_test_sample)
    elif "Logistic" in model_name:
        explainer = shap.LinearExplainer(classifier, X_test_sample)
        shap_values = explainer(X_test_sample)
    else:
        explainer = shap.Explainer(classifier, X_test_sample)
        shap_values = explainer(X_test_sample)
        
    # Determine dimensionality of SHAP values
    if len(shap_values.values.shape) == 3:
        shap_imp_raw = np.abs(shap_values.values[:, :, 1]).mean(axis=0)
        shap_values_to_plot = shap_values[:, :, 1]
    else:
        shap_imp_raw = np.abs(shap_values.values).mean(axis=0)
        shap_values_to_plot = shap_values
        
    # Map transformed feature importances back to original 21 predictor names
    shap_imp_dict = {col: 0.0 for col in X_test.columns}
    for i, col in enumerate(X_test_sample.columns):
        matched = False
        for orig in X_test.columns:
            if orig in col:
                shap_imp_dict[orig] += shap_imp_raw[i]
                matched = True
                break
        if not matched:
            shap_imp_dict[col] = shap_imp_raw[i]
            
    shap_imp_df = pd.DataFrame([
        {"Variable": col, "SHAP_Importance": shap_imp_dict[col]}
        for col in X_test.columns
    ]).sort_values(by="SHAP_Importance", ascending=False)
    
    shap_imp_df["SHAP_Rank"] = shap_imp_df["SHAP_Importance"].rank(ascending=False).astype(int)
    
    # 1. Save Global SHAP Bar Plot
    plt.figure(figsize=(10, 6))
    shap.summary_plot(shap_values_to_plot, X_test_sample, plot_type="bar", show=False)
    plt.title(f"SHAP Global Feature Importance ({model_name})", fontsize=13, fontweight="bold", pad=20)
    plt.xlabel("Mean |SHAP Value| (Predictive Feature Contribution)", fontsize=11, labelpad=10)
    plt.gcf().tight_layout()
    plt.savefig(XAI_DIR / "shap_summary_bar.png", dpi=300, bbox_inches="tight")
    plt.savefig(DOCS_FIG_DIR / "shap_global_importance.png", dpi=300, bbox_inches="tight")
    plt.savefig(DOCS_FIG_DIR / "shap_global_importance.svg", format="svg", bbox_inches="tight")
    plt.close()
    
    # 2. Save Global SHAP Beeswarm Plot
    plt.figure(figsize=(10, 6))
    shap.summary_plot(shap_values_to_plot, X_test_sample, show=False)
    plt.title(f"SHAP Global Feature Impact ({model_name})", fontsize=13, fontweight="bold", pad=20)
    plt.xlabel("SHAP Value (Impact on Log-Odds Output)", fontsize=11, labelpad=10)
    plt.gcf().tight_layout()
    plt.savefig(XAI_DIR / "shap_summary_dot.png", dpi=300, bbox_inches="tight")
    plt.savefig(DOCS_FIG_DIR / "shap_summary_beeswarm.png", dpi=300, bbox_inches="tight")
    plt.savefig(DOCS_FIG_DIR / "shap_summary_beeswarm.svg", format="svg", bbox_inches="tight")
    plt.close()
    
    # 3. Save Local Explanations (Survey Respondents)
    y_prob_sample = pipeline.predict_proba(X_raw_sample)[:, 1]
    y_test_arr = y_test_sample.values
    
    high_risk_indices = np.where((y_test_arr == 1) & (y_prob_sample > 0.50))[0]
    if len(high_risk_indices) > 0:
        idx_high = high_risk_indices[0]
        plt.figure(figsize=(10, 6))
        shap.plots.waterfall(shap_values_to_plot[idx_high], max_display=8, show=False)
        plt.title(f"SHAP Local Explanation (High-Risk Survey Respondent Profile, Predicted Prob={y_prob_sample[idx_high]:.2%})", fontsize=11, fontweight="bold", pad=15)
        plt.savefig(XAI_DIR / "shap_local_diabetic.png", dpi=300, bbox_inches="tight")
        plt.savefig(DOCS_FIG_DIR / "shap_local_high_risk.png", dpi=300, bbox_inches="tight")
        plt.savefig(DOCS_FIG_DIR / "shap_local_high_risk.svg", format="svg", bbox_inches="tight")
        plt.close()
        
    low_risk_indices = np.where((y_test_arr == 0) & (y_prob_sample < 0.10))[0]
    if len(low_risk_indices) > 0:
        idx_low = low_risk_indices[0]
        plt.figure(figsize=(10, 6))
        shap.plots.waterfall(shap_values_to_plot[idx_low], max_display=8, show=False)
        plt.title(f"SHAP Local Explanation (Low-Risk Survey Respondent Profile, Predicted Prob={y_prob_sample[idx_low]:.2%})", fontsize=11, fontweight="bold", pad=15)
        plt.savefig(XAI_DIR / "shap_local_healthy.png", dpi=300, bbox_inches="tight")
        plt.close()
        
    print("Saved global and local SHAP plots successfully.")
    return shap_imp_df

def perform_consistency_analysis(shap_imp_df):
    """Executes Effect-Size–SHAP Evidence Alignment analysis with 4 groups and quantitative metrics."""
    print("\nExecuting Statistical–SHAP Evidence Alignment Analysis...")
    
    chi_path = RESULTS_STAT_DIR / "chi_square_results.csv"
    num_path = RESULTS_STAT_DIR / "numerical_results.csv"
    
    if not (chi_path.exists() and num_path.exists()):
        raise FileNotFoundError("Statistical results from Phase 2 not found. Run statistical_analysis.py first.")
        
    chi_df = pd.read_csv(chi_path)
    num_df = pd.read_csv(num_path)
    
    stat_list = []
    for _, row in chi_df.iterrows():
        var = row["Variable"].strip()
        v = float(row["Cramér's V"])
        stat_list.append({
            "Variable": var,
            "Description": row["Description"],
            "p_value": float(row["p-value"]),
            "Holm_p_value": float(row["Holm_p_value"]),
            "Effect_Size": v,
            "Effect_Size_Type": "Cramér's V",
            "Meaningful_Marginal_Effect": "Yes" if v >= 0.05 else "No"
        })
    for _, row in num_df.iterrows():
        var = row["Variable"].strip()
        rb = abs(float(row["Rank-Biserial Correlation"]))
        stat_list.append({
            "Variable": var,
            "Description": LABEL_MAPPING.get(var, var),
            "p_value": float(row["MWU p-value"]),
            "Holm_p_value": float(row["Holm_p_value"]),
            "Effect_Size": rb,
            "Effect_Size_Type": "Abs Rank-Biserial",
            "Meaningful_Marginal_Effect": "Yes" if rb >= 0.10 else "No"
        })
        
    stat_df = pd.DataFrame(stat_list)
    
    # Percentile rank within effect size type to derive global evidence rank
    stat_df["Effect_Size_Percentile"] = stat_df.groupby("Effect_Size_Type")["Effect_Size"].rank(pct=True)
    stat_df["Effect_Size_Rank"] = stat_df["Effect_Size_Percentile"].rank(ascending=False).astype(int)
    
    merged = pd.merge(shap_imp_df, stat_df, on="Variable").sort_values(by="SHAP_Rank")
    merged["SHAP_Percentile"] = merged["SHAP_Importance"].rank(pct=True)
    
    # 4 Alignment Groups
    groups = []
    interpretations = []
    
    for _, row in merged.iterrows():
        meaningful = (row["Meaningful_Marginal_Effect"] == "Yes")
        high_shap = (row["SHAP_Rank"] <= 10)
        
        if meaningful and high_shap:
            grp = "Group 1 — Consistent high evidence"
            interp = "Meaningful marginal association within the analyzed BRFSS sample and high model salience."
        elif meaningful and not high_shap:
            grp = "Group 2 — Meaningful marginal association, lower model salience"
            interp = "The feature shows a meaningful marginal association within the analyzed sample but is not among the highest SHAP-ranked predictors. This may reflect shared information, correlation, or limited incremental contribution after other predictors are considered."
        elif not meaningful and high_shap:
            grp = "Group 3 — Model-salient, weak marginal association"
            interp = "The feature exhibits lower univariate marginal association in the sample but makes non-negligible contributions in the multivariate predictive model."
        else:
            grp = "Group 4 — Weak evidence"
            interp = "Weak evidence within the current dataset and model does not imply that the feature has no medical relevance."
            
        groups.append(grp)
        interpretations.append(interp)
        
    merged["Consistency_Group"] = groups
    merged["Consistency_Interpretation"] = interpretations
    
    # Quantitative Consensus Metrics
    top10_shap = set(merged[merged["SHAP_Rank"] <= 10]["Variable"])
    top10_stat = set(merged[merged["Effect_Size_Rank"] <= 10]["Variable"])
    
    overlap_count = len(top10_shap.intersection(top10_stat))
    jaccard_sim = overlap_count / len(top10_shap.union(top10_stat))
    spearman_corr, spearman_p = spearmanr(merged["SHAP_Rank"], merged["Effect_Size_Rank"])
    
    print("\n--- Exploratory Rank-Alignment Diagnostics ---")
    print(f"Top-10 Overlap Count: {overlap_count} / 10 features")
    print(f"Top-10 Jaccard Similarity: {jaccard_sim:.4f}")
    print(f"Spearman Rank Correlation (SHAP Rank vs Effect Size Rank): r = {spearman_corr:.4f} (p = {spearman_p:.4e})")
    
    # Group breakdown
    g1_list = merged[merged["Consistency_Group"].str.startswith("Group 1")]["Variable"].tolist()
    g2_list = merged[merged["Consistency_Group"].str.startswith("Group 2")]["Variable"].tolist()
    g3_list = merged[merged["Consistency_Group"].str.startswith("Group 3")]["Variable"].tolist()
    g4_list = merged[merged["Consistency_Group"].str.startswith("Group 4")]["Variable"].tolist()
    
    print(f"Group 1 (Consistent High Evidence): {g1_list}")
    print(f"Group 2 (Meaningful Marginal, Lower Model Salience): {g2_list}")
    print(f"Group 3 (Model Salient, Weak Marginal): {g3_list}")
    print(f"Group 4 (Weak Evidence): {g4_list}")
    
    merged.to_csv(XAI_DIR / "explanation_consistency.csv", index=False)
    
    # Generate Scatter Figure
    fig, ax = plt.subplots(figsize=(10, 7.5))
    
    color_map = {
        "Group 1 — Consistent high evidence": "#059669",
        "Group 2 — Meaningful marginal association, lower model salience": "#2563EB",
        "Group 3 — Model-salient, weak marginal association": "#D97706",
        "Group 4 — Weak evidence": "#64748B"
    }
    
    for grp_name, grp_df in merged.groupby("Consistency_Group"):
        ax.scatter(
            grp_df["Effect_Size_Percentile"] * 100,
            grp_df["SHAP_Percentile"] * 100,
            color=color_map.get(grp_name, "#333333"),
            label=grp_name,
            s=110,
            edgecolor="#0F172A",
            linewidth=0.8,
            zorder=4
        )
        for _, row in grp_df.iterrows():
            ax.annotate(
                row["Variable"],
                (row["Effect_Size_Percentile"] * 100, row["SHAP_Percentile"] * 100),
                xytext=(5, 5), textcoords="offset points",
                fontsize=8.5, fontweight="bold", color="#1E293B", zorder=5
            )
            
    ax.set_xlabel("Sample-Level Effect-Size Evidence Percentile", fontsize=10.5, fontweight="bold")
    ax.set_ylabel("SHAP Model Importance Percentile Rank", fontsize=10.5, fontweight="bold")
    ax.set_title(f"Effect-Size–SHAP Evidence Alignment Framework\n(Exploratory Diagnostics: Top-10 Jaccard = {jaccard_sim:.2f}, Spearman r = {spearman_corr:.2f})", fontsize=12, fontweight="bold", pad=15)
    ax.legend(loc="lower left", fontsize=8.5, frameon=True, facecolor="white", framealpha=0.95)
    
    plt.tight_layout()
    fig.subplots_adjust(bottom=0.12)
    fig.text(0.5, 0.02, "Groups are defined using prespecified meaningful-effect thresholds and Top-10 SHAP membership; percentile axes are used only for visualization.", ha="center", fontsize=8.5, fontstyle="italic", color="#475569")
    
    plt.savefig(XAI_DIR / "consistency_quadrant.png", dpi=300)
    plt.savefig(DOCS_FIG_DIR / "effect_size_shap_alignment.png", dpi=300)
    plt.savefig(DOCS_FIG_DIR / "effect_size_shap_alignment.svg", format="svg", bbox_inches="tight")
    plt.close()
    
    return merged

def main():
    print("=== Phase 5: Explainable AI & Evidence Alignment Analysis ===")
    
    try:
        df = load_data(DATA_PATH)
    except FileNotFoundError as e:
        print(e)
        return
        
    X = df.drop(columns=["Diabetes_binary"])
    y = df["Diabetes_binary"]
    
    X_dev, X_test, y_dev, y_test = train_test_split(
        X, y, test_size=0.20, stratify=y, random_state=42
    )
    
    pipeline, model_name, selected_threshold, metadata = load_selected_model()
    
    shap_imp_df = run_shap_analysis(pipeline, model_name, X_test, y_test)
    perform_consistency_analysis(shap_imp_df)
    
    print("\n=== Explainable AI Module Completed Successfully ===")

if __name__ == "__main__":
    main()
